### ISSUE TITLE
hubotとgithubを連携する

### ISSUE THREAD

**Issue by shu920921** [ryo2851/gitnotification#2]

**Comment by ryo2851** [comment]
issue#3に着手するためパス

**Comment by shu920921** [comment]
[このページ](http://blog.spacemarket.com/code/hubot-github-webhook-1/)を参考にしてやっていきます

**Comment by shu920921** [comment]
@ryo2851 
>チャットツールにHubot経由で発言できている
>Hubot Adapter経由でチャットツールに接続できているという意味です
>GitHubからアクセスできる場所(Heroku上など)でHubotを稼働させている
>GitHubのWebhookを利用する関係上、外部からアクセスできることが必須となります

と参考ページに書いてあったから #3 の方が早く着手されそうな感じがする
